export const ACADEMY_LIST_REQUEST = "ACADEMY_LIST_REQUEST";
export const ACADEMY_LIST_SUCCESS = "ACADEMY_LIST_SUCCESS";
export const ACADEMY_LIST_FAIL = "ACADEMY_LIST_FAIL";

export const ACADEMY_LIST_SEARCH_REQUEST = "ACADEMY_LIST_SEARCH_REQUEST";
export const ACADEMY_LIST_SEARCH_SUCCESS = "ACADEMY_LIST_SEARCH_SUCCESS";
export const ACADEMY_LIST_SEARCH_FAIL = "ACADEMY_LIST_SEARCH_FAIL";

export const ACADEMY_LIST_SEARCH_CATEGORY_REQUEST = "ACADEMY_LIST_SEARCH_CATEGORY_REQUEST";
export const ACADEMY_LIST_SEARCH_CATEGORY_SUCCESS = "ACADEMY_LIST_SEARCH_CATEGORY_SUCCESS";
export const ACADEMY_LIST_SEARCH_CATEGORY_FAIL = "ACADEMY_LIST_SEARCH_CATEGORY_FAIL";

export const ACADEMY_CATEGORY_LIST_REQUEST = "ACADEMY_CATEGORY_LIST_REQUEST";
export const ACADEMY_CATEGORY_LIST_SUCCESS = "ACADEMY_CATEGORY_LIST_SUCCESS";
export const ACADEMY_CATEGORY_LIST_FAIL = "ACADEMY_CATEGORY_LIST_FAIL";

export const ACADEMY_LIST_RELATED_REQUEST = "ACADEMY_LIST_RELATED_REQUEST";
export const ACADEMY_LIST_RELATED_SUCCESS = "ACADEMY_LIST_RELATED_SUCCESS";
export const ACADEMY_LIST_RELATED_FAIL = "ACADEMY_LIST_RELATED_FAIL";

export const ACADEMY_DETAILS_REQUEST = "ACADEMY_DETAILS_REQUEST";
export const ACADEMY_DETAILS_SUCCESS = "ACADEMY_DETAILS_SUCCESS";
export const ACADEMY_DETAILS_FAIL = "ACADEMY_DETAILS_FAIL";

